/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { ComponentProps, Suspense, use, useCallback, useEffect, useMemo, useRef, useState } from "react";
import { useGLTF, useAnimations, useHelper, useVideoTexture, } from "@react-three/drei";
import { GroupProps, useFrame } from "@react-three/fiber";
import { Group, SpotLight, SpotLightHelper, PerspectiveCamera, CameraHelper, MeshBasicMaterial, MeshPhysicalMaterial, AnimationMixer, PointLight, PointLightHelper, } from "three";
import { useSpring, animated, config, AnimatedComponent } from '@react-spring/three'
import { MeshBasicMaterialProps } from '@react-three/fiber'
import { useShadowHelper } from "@/app/(hooks)/use-camera-shadow-helper";
import { RectAreaLightHelper } from 'three/examples/jsm/helpers/RectAreaLightHelper';
import { GLTF } from "three-stdlib";
import { LampLightSource } from "./lights";
import { timeStamp } from "console";
import { AnimationStates } from "../main-canvas";

type GLTFResult = GLTF & {
  nodes: {
    Plane005: THREE.Mesh;
    Plane005_1: THREE.Mesh;
    Plane022: THREE.SkinnedMesh;
    Plane022_1: THREE.SkinnedMesh;
    Cube014: THREE.Mesh;
    Cube014_1: THREE.Mesh;
    Cube090: THREE.Mesh;
    Cube090_1: THREE.Mesh;
    Cabinet: THREE.Mesh;
    Carpet: THREE.Mesh;
    Entrance_mat: THREE.Mesh;
    Cabinet_shelf_top: THREE.Mesh;
    Cabinet_shelf_middle: THREE.Mesh;
    Cabinet_shelf_bottom: THREE.Mesh;
    fish: THREE.Mesh;
    Aquarium_glass: THREE.Mesh;
    Aquarium_roof: THREE.Mesh;
    Aquarium_bottom: THREE.Mesh;
    Aquarium_glass001: THREE.Mesh;
    Aquarium_glass002: THREE.Mesh;
    Rocks_and_stuff: THREE.Mesh;
    Rocks_and_stuff001: THREE.Mesh;
    Rocks_and_stuff002: THREE.Mesh;
    Rocks_and_stuff003: THREE.Mesh;
    Rocks_and_stuff004: THREE.Mesh;
    Rocks_and_stuff005: THREE.Mesh;
    Rocks_and_stuff006: THREE.Mesh;
    Rocks_and_stuff007: THREE.Mesh;
    Rocks_and_stuff008: THREE.Mesh;
    Rocks_and_stuff009: THREE.Mesh;
    Rocks_and_stuff010: THREE.Mesh;
    Rocks_and_stuff011: THREE.Mesh;
    Rocks_and_stuff012: THREE.Mesh;
    Rocks_and_stuff013: THREE.Mesh;
    Rocks_and_stuff014: THREE.Mesh;
    Rocks_and_stuff015: THREE.Mesh;
    Rocks_and_stuff016: THREE.Mesh;
    Rocks_and_stuff017: THREE.Mesh;
    Rocks_and_stuff018: THREE.Mesh;
    Rocks_and_stuff019: THREE.Mesh;
    Rocks_and_stuff020: THREE.Mesh;
    Rocks_and_stuff021: THREE.Mesh;
    Rocks_and_stuff022: THREE.Mesh;
    Rocks_and_stuff023: THREE.Mesh;
    Rocks_and_stuff024: THREE.Mesh;
    Rocks_and_stuff025: THREE.Mesh;
    Aquarium_plant004: THREE.Mesh;
    Aquarium_plant: THREE.Mesh;
    Aquarium_seaweed: THREE.Mesh;
    Aquarium_plant001: THREE.Mesh;
    Aquarium_plant002: THREE.Mesh;
    Aquarium_plant003: THREE.Mesh;
    Aquarium_seaweed001: THREE.Mesh;
    Aquarium_seaweed002: THREE.Mesh;
    Aquarium_seaweed003: THREE.Mesh;
    Aquarium_seaweed004: THREE.Mesh;
    Aquarium_seaweed005: THREE.Mesh;
    Aquarium_seaweed006: THREE.Mesh;
    FloorFirst: THREE.Mesh;
    Dirt: THREE.Mesh;
    FloorSecond: THREE.Mesh;
    FloorThird: THREE.Mesh;
    Cylinder021: THREE.Mesh;
    Cylinder021_1: THREE.Mesh;
    Cylinder021_2: THREE.Mesh;
    Plane010: THREE.Mesh;
    Plane010_1: THREE.Mesh;
    Cylinder_1: THREE.Mesh;
    Cylinder_2: THREE.Mesh;
    Cube081: THREE.Mesh;
    Cube081_1: THREE.Mesh;
    Cylinder014: THREE.Mesh;
    Cylinder014_1: THREE.Mesh;
    Cylinder014_2: THREE.Mesh;
    Cube006: THREE.Mesh;
    Cube006_1: THREE.Mesh;
    Cube006_2: THREE.Mesh;
    Cube007: THREE.Mesh;
    Cube007_1: THREE.Mesh;
    Cube085: THREE.Mesh;
    Cube085_1: THREE.Mesh;
    Cube085_2: THREE.Mesh;
    Cube085_3: THREE.Mesh;
    Cube085_4: THREE.Mesh;
    Cube088: THREE.Mesh;
    Cube088_1: THREE.Mesh;
    Cube088_2: THREE.Mesh;
    Cube088_3: THREE.Mesh;
    Cube128: THREE.Mesh;
    Cube128_1: THREE.Mesh;
    Cube002: THREE.Mesh;
    Cube002_1: THREE.Mesh;
    Cube003: THREE.Mesh;
    Cube003_1: THREE.Mesh;
    Cube004: THREE.Mesh;
    Cube004_1: THREE.Mesh;
    Cube005: THREE.Mesh;
    Cube005_1: THREE.Mesh;
    Chair: THREE.Mesh;
    Chair_legs: THREE.Mesh;
    Clock: THREE.Mesh;
    Cylinder001_1: THREE.Mesh;
    Cylinder001_2: THREE.Mesh;
    Cylinder006_1: THREE.Mesh;
    Cylinder006_2: THREE.Mesh;
    Ceiling_lamp: THREE.Mesh;
    Ceiling_lamp_rod: THREE.Mesh;
    Couch: THREE.Mesh;
    Cushion_1: THREE.Mesh;
    Cushion_2: THREE.Mesh;
    Cushion_3: THREE.Mesh;
    Pillow: THREE.Mesh;
    Blanket: THREE.Mesh;
    Shelves: THREE.Mesh;
    Shelves001: THREE.Mesh;
    Shelves002: THREE.Mesh;
    Cube072: THREE.Mesh;
    Cube072_1: THREE.Mesh;
    Cube073: THREE.Mesh;
    Cube073_1: THREE.Mesh;
    Cube074: THREE.Mesh;
    Cube074_1: THREE.Mesh;
    Cube075: THREE.Mesh;
    Cube075_1: THREE.Mesh;
    Cube076: THREE.Mesh;
    Cube076_1: THREE.Mesh;
    Cube077: THREE.Mesh;
    Cube077_1: THREE.Mesh;
    Cube078: THREE.Mesh;
    Cube078_1: THREE.Mesh;
    Cube084: THREE.Mesh;
    Cube084_1: THREE.Mesh;
    Cube116: THREE.Mesh;
    Cube116_1: THREE.Mesh;
    Cube079: THREE.Mesh;
    Cube079_1: THREE.Mesh;
    Cube070: THREE.Mesh;
    Cube070_1: THREE.Mesh;
    Cube070_2: THREE.Mesh;
    Cylinder009: THREE.Mesh;
    Cylinder009_1: THREE.Mesh;
    Cylinder010: THREE.Mesh;
    Cylinder010_1: THREE.Mesh;
    Cylinder011: THREE.Mesh;
    Cylinder011_1: THREE.Mesh;
    Cylinder012: THREE.Mesh;
    Cylinder012_1: THREE.Mesh;
    Mother_bone: THREE.Bone;
  };
  materials: {
    Walls: THREE.MeshPhysicalMaterial;
    ["Wall 2"]: THREE.MeshStandardMaterial;
    ["Monitor frame"]: THREE.MeshStandardMaterial;
    ["Monitor screen"]: THREE.MeshStandardMaterial;
    ["Trash lid"]: THREE.MeshStandardMaterial;
    ["Desk top.001"]: THREE.MeshPhysicalMaterial;
    Rug: THREE.MeshStandardMaterial;
    ["Floor tile 2"]: THREE.MeshStandardMaterial;
    Fish: THREE.MeshPhysicalMaterial;
    ["Fish tank"]: THREE.MeshStandardMaterial;
    ["Fish tank holder"]: THREE.MeshStandardMaterial;
    Rock: THREE.MeshStandardMaterial;
    ["Fish tank thing 1"]: THREE.MeshStandardMaterial;
    ["Fish thank thing 3"]: THREE.MeshStandardMaterial;
    Seaweed: THREE.MeshStandardMaterial;
    ["Fish tank thing 2"]: THREE.MeshStandardMaterial;
    ["Floor tile 1"]: THREE.MeshStandardMaterial;
    Dirt: THREE.MeshStandardMaterial;
    ["Floor tile 3"]: THREE.MeshStandardMaterial;
    Pages: THREE.MeshStandardMaterial;
    ["Book cover blue"]: THREE.MeshStandardMaterial;
    Lamp: THREE.MeshPhysicalMaterial;
    ["Lamp light"]: THREE.MeshStandardMaterial;
    Sign: THREE.MeshStandardMaterial;
    ["Welcome text"]: THREE.MeshStandardMaterial;
    ["Side floor"]: THREE.MeshStandardMaterial;
    ["Desk legs.001"]: THREE.MeshStandardMaterial;
    ["Desk leg black.001"]: THREE.MeshPhysicalMaterial;
    Leaves: THREE.MeshStandardMaterial;
    Pot: THREE.MeshStandardMaterial;
    ["Trackpad base"]: THREE.MeshStandardMaterial;
    ["Trackpad face"]: THREE.MeshStandardMaterial;
    ["Pencil base 2"]: THREE.MeshStandardMaterial;
    ["Pencil holder"]: THREE.MeshStandardMaterial;
    ["Pencil head"]: THREE.MeshStandardMaterial;
    ["Pencil lead"]: THREE.MeshStandardMaterial;
    ["Pencil base"]: THREE.MeshStandardMaterial;
    ["White keys"]: THREE.MeshStandardMaterial;
    ["Blue keys"]: THREE.MeshStandardMaterial;
    ["Orange keys"]: THREE.MeshStandardMaterial;
    Keyboard: THREE.MeshStandardMaterial;
    ["Table legs"]: THREE.MeshStandardMaterial;
    Table: THREE.MeshStandardMaterial;
    Mug: THREE.MeshStandardMaterial;
    ["Book cover green"]: THREE.MeshStandardMaterial;
    Chair: THREE.MeshStandardMaterial;
    ["Ceiling light"]: THREE.MeshStandardMaterial;
    ["Ceiling rod"]: THREE.MeshStandardMaterial;
    Couch: THREE.MeshStandardMaterial;
    ["Couch cushions"]: THREE.MeshStandardMaterial;
    Pillow: THREE.MeshStandardMaterial;
    Blanket: THREE.MeshStandardMaterial;
    ["Book cover red"]: THREE.MeshStandardMaterial;
    ["Book cover brown"]: THREE.MeshStandardMaterial;
    ["Box top"]: THREE.MeshStandardMaterial;
    ["Picture frame"]: THREE.MeshStandardMaterial;
    Picture: THREE.MeshStandardMaterial;
    ["Lamp base"]: THREE.MeshStandardMaterial;
    ["Pot 2"]: THREE.MeshStandardMaterial;
    ["Bottle 1"]: THREE.MeshStandardMaterial;
    ["Bottle cap"]: THREE.MeshStandardMaterial;
    ["Bottle 2"]: THREE.MeshStandardMaterial;
    ["Bottle 3"]: THREE.MeshStandardMaterial;
    ["Bottle 4"]: THREE.MeshStandardMaterial;
  };
};

type ActionName =
  | "Body"
  | "ArmatureAction"
  | "ComputerAction"
  | "Garbage canAction"
  | "CabinetAction"
  | "CarpetAction"
  | "Entrance matAction"
  | "Cabinet shelf topAction"
  | "Cabinet shelf middleAction"
  | "Cabinet shelf bottomAction"
  | "FishAction"
  | "Aquarium glassAction"
  | "Aquarium roofAction"
  | "Aquarium bottomAction"
  | "Aquarium glass.001Action"
  | "Aquarium glass.003Action"
  | "Rocks and stuffAction"
  | "Rocks and stuff.001Action"
  | "Rocks and stuff.002Action"
  | "Rocks and stuff.003Action"
  | "Rocks and stuff.004Action"
  | "Rocks and stuff.005Action"
  | "Rocks and stuff.006Action"
  | "Rocks and stuff.007Action"
  | "Rocks and stuff.008Action"
  | "Rocks and stuff.009Action"
  | "Rocks and stuff.010Action"
  | "Rocks and stuff.011Action"
  | "Rocks and stuff.012Action"
  | "Rocks and stuff.013Action"
  | "Rocks and stuff.014Action"
  | "Rocks and stuff.015Action"
  | "Rocks and stuff.016Action"
  | "Rocks and stuff.017Action"
  | "Rocks and stuff.018Action"
  | "Rocks and stuff.019Action"
  | "Rocks and stuff.020Action"
  | "Rocks and stuff.021Action"
  | "Rocks and stuff.022Action"
  | "Rocks and stuff.023Action"
  | "Rocks and stuff.024Action"
  | "Rocks and stuff.025Action"
  | "Rocks and stuff.028Action"
  | "Rocks and stuff.030Action"
  | "Rocks and stuff.037Action"
  | "Rocks and stuff.028Action.001"
  | "Rocks and stuff.028Action.002"
  | "Rocks and stuff.028Action.003"
  | "Rocks and stuff.037Action.001"
  | "Rocks and stuff.037Action.002"
  | "Rocks and stuff.037Action.003"
  | "Rocks and stuff.037Action.004"
  | "Rocks and stuff.037Action.005"
  | "Rocks and stuff.037Action.006"
  | "FloorFirstAction"
  | "DirtAction"
  | "FloorSecondAction"
  | "FloorThirdAction"
  | "MailboxAction"
  | "LampAction"
  | "WelcomeSignAction"
  | "Mini floorAction"
  | "DesksAction"
  | "Desk plantAction.001"
  | "MousepadAction.001"
  | "Pencil caseAction.001"
  | "KeyboardAction.001"
  | "TableAction"
  | "Table itemsAction.001"
  | "Table itemsAction.002"
  | "Table itemsAction.003"
  | "Table itemsAction.004"
  | "ChairAction"
  | "Floor items.002Action.001"
  | "ClockAction"
  | "Clock.001Action"
  | "Clock.002Action"
  | "Ceiling lampAction"
  | "Ceiling lamp rodAction"
  | "CouchAction.001"
  | "Cushion 1Action"
  | "Cushion 2Action"
  | "Cushion 3Action"
  | "PillowAction"
  | "BlanketAction"
  | "ShelvesAction"
  | "Shelves.001Action"
  | "Shelves.002Action"
  | "Book 1Action"
  | "Book 2Action"
  | "Book 3Action"
  | "Book 4Action"
  | "Book 5Action"
  | "Book 6Action"
  | "Book 7Action"
  | "BoxAction.015"
  | "Picture frameAction"
  | "Shelf lampAction"
  | "Shelf plantAction"
  | "CylinderAction"
  | "Cylinder.001Action"
  | "Cylinder.005Action"
  | "Cylinder.006Action";
type GLTFActions = Record<ActionName, THREE.AnimationAction>;

function VideoMaterial({ url, ...props }: { url: string } & MeshBasicMaterialProps) {
    // https://codesandbox.io/s/video-texture-39hg8?file=/src/App.js:512-650
    const texture = useVideoTexture(url)
    texture.flipY = false;
    // console.log({ texture })
    return <meshBasicMaterial map={texture}  {...props} />
}

type RoomModelProps = ComponentProps<typeof animated.group> & {
    animationState: AnimationStates;
    progressAnimationState: (state?: AnimationStates) => void;
}

export function RoomModel({ animationState, progressAnimationState, ...props }: RoomModelProps) {
  const group = useRef<Group>(null);
  const { nodes, materials, animations } = useGLTF("/models/website ver2.glb") as GLTFResult;
  const { actions } = useAnimations(animations, group);

  useEffect(() => { 
    if (actions.ArmatureAction) {
        actions.ArmatureAction.play();
    }
});

console.log(nodes)

  return (
    <animated.group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group
          name="Body"
          position={[0.003, 0, 0.455]}
          rotation={[0, 0.001, -Math.PI / 2]}
        >
          <mesh
            name="Plane005"
            castShadow
            receiveShadow
            geometry={nodes.Plane005.geometry}
            material={materials.Walls}
          />
          <mesh
            name="Plane005_1"
            castShadow
            receiveShadow
            geometry={nodes.Plane005_1.geometry}
            material={materials["Wall 2"]}
          />
        </group>
        <group name="Cover" position={[0.553, 12.167, -0.133]} scale={8.75}>
          <group name="Plane">
            <skinnedMesh
              name="Plane022"
              geometry={nodes.Plane022.geometry}
              material={materials.Walls}
              skeleton={nodes.Plane022.skeleton}
            />
            <skinnedMesh
              name="Plane022_1"
              geometry={nodes.Plane022_1.geometry}
              material={materials["Wall 2"]}
              skeleton={nodes.Plane022_1.skeleton}
            />
          </group>
          <primitive object={nodes.Mother_bone} />
        </group>
        <group name="Computer" position={[33.668, 5.176, 3.196]} scale={0}>
          <mesh
            name="Cube014"
            castShadow
            receiveShadow
            geometry={nodes.Cube014.geometry}
            material={materials["Monitor frame"]}
          />
          <mesh
            name="Cube014_1"
            castShadow
            receiveShadow
            geometry={nodes.Cube014_1.geometry}
            material={materials["Monitor screen"]}
          />
        </group>
        <group name="Garbage_can" position={[36.001, 2.336, 5.841]} scale={0}>
          <mesh
            name="Cube090"
            castShadow
            receiveShadow
            geometry={nodes.Cube090.geometry}
            material={materials["Trash lid"]}
          />
          <mesh
            name="Cube090_1"
            castShadow
            receiveShadow
            geometry={nodes.Cube090_1.geometry}
            material={materials["Desk top.001"]}
          />
        </group>
        <mesh
          name="Cabinet"
          castShadow
          receiveShadow
          geometry={nodes.Cabinet.geometry}
          material={materials["Desk top.001"]}
          position={[-4.47, 2.549, 0.732]}
          scale={0}
        />
        <mesh
          name="Carpet"
          castShadow
          receiveShadow
          geometry={nodes.Carpet.geometry}
          material={materials.Rug}
          position={[3.281, 31.211, 0.789]}
          scale={0}
        />
        <mesh
          name="Entrance_mat"
          castShadow
          receiveShadow
          geometry={nodes.Entrance_mat.geometry}
          material={materials["Floor tile 2"]}
          position={[3.172, 31.187, 6.049]}
          scale={0}
        />
        <mesh
          name="Cabinet_shelf_top"
          castShadow
          receiveShadow
          geometry={nodes.Cabinet_shelf_top.geometry}
          material={materials["Desk top.001"]}
          position={[-11.092, 6.77, 1.712]}
          scale={0}
        />
        <mesh
          name="Cabinet_shelf_middle"
          castShadow
          receiveShadow
          geometry={nodes.Cabinet_shelf_middle.geometry}
          material={materials["Desk top.001"]}
          position={[-11.242, 5.587, 1.642]}
          scale={0}
        />
        <mesh
          name="Cabinet_shelf_bottom"
          castShadow
          receiveShadow
          geometry={nodes.Cabinet_shelf_bottom.geometry}
          material={materials["Desk top.001"]}
          position={[-11.242, 4.424, 1.642]}
          scale={0}
        />
        <mesh
          name="fish"
          castShadow
          receiveShadow
          geometry={nodes.fish.geometry}
          material={materials.Fish}
          position={[7.3, 4.929, -6.94]}
          scale={0}
        />
        <mesh
          name="Aquarium_glass"
          castShadow
          receiveShadow
          geometry={nodes.Aquarium_glass.geometry}
          material={materials["Fish tank"]}
          position={[5.472, 4.837, 36.001]}
          scale={0}
        />
        <mesh
          name="Aquarium_roof"
          castShadow
          receiveShadow
          geometry={nodes.Aquarium_roof.geometry}
          material={materials["Fish tank holder"]}
          position={[5.471, 27.18, -5.741]}
          scale={0}
        />
        <mesh
          name="Aquarium_bottom"
          castShadow
          receiveShadow
          geometry={nodes.Aquarium_bottom.geometry}
          material={materials["Fish tank holder"]}
          position={[5.471, 32.18, -5.741]}
          scale={0}
        />
        <mesh
          name="Aquarium_glass001"
          castShadow
          receiveShadow
          geometry={nodes.Aquarium_glass001.geometry}
          material={materials["Fish tank"]}
          position={[9.976, 2.18, 33.236]}
          scale={0}
        />
        <mesh
          name="Aquarium_glass002"
          castShadow
          receiveShadow
          geometry={nodes.Aquarium_glass002.geometry}
          material={materials["Fish tank"]}
          position={[0.957, 2.18, 33.217]}
          scale={0}
        />
        <mesh
          name="Rocks_and_stuff"
          castShadow
          receiveShadow
          geometry={nodes.Rocks_and_stuff.geometry}
          material={materials.Rock}
          position={[5.471, 29.18, -5.741]}
          scale={0}
        />
        <mesh
          name="Rocks_and_stuff001"
          castShadow
          receiveShadow
          geometry={nodes.Rocks_and_stuff001.geometry}
          material={materials.Rock}
          position={[5.471, 29.18, -5.741]}
          scale={0}
        />
        <mesh
          name="Rocks_and_stuff002"
          castShadow
          receiveShadow
          geometry={nodes.Rocks_and_stuff002.geometry}
          material={materials.Rock}
          position={[5.471, 29.18, -5.741]}
          scale={0}
        />
        <mesh
          name="Rocks_and_stuff003"
          castShadow
          receiveShadow
          geometry={nodes.Rocks_and_stuff003.geometry}
          material={materials.Rock}
          position={[5.471, 29.18, -5.741]}
          scale={0}
        />
        <mesh
          name="Rocks_and_stuff004"
          castShadow
          receiveShadow
          geometry={nodes.Rocks_and_stuff004.geometry}
          material={materials.Rock}
          position={[5.471, 29.18, -5.741]}
          scale={0}
        />
        <mesh
          name="Rocks_and_stuff005"
          castShadow
          receiveShadow
          geometry={nodes.Rocks_and_stuff005.geometry}
          material={materials.Rock}
          position={[5.471, 29.18, -5.741]}
          scale={0}
        />
        <mesh
          name="Rocks_and_stuff006"
          castShadow
          receiveShadow
          geometry={nodes.Rocks_and_stuff006.geometry}
          material={materials.Rock}
          position={[5.471, 29.18, -5.741]}
          scale={0}
        />
        <mesh
          name="Rocks_and_stuff007"
          castShadow
          receiveShadow
          geometry={nodes.Rocks_and_stuff007.geometry}
          material={materials.Rock}
          position={[5.471, 29.18, -5.741]}
          scale={0}
        />
        <mesh
          name="Rocks_and_stuff008"
          castShadow
          receiveShadow
          geometry={nodes.Rocks_and_stuff008.geometry}
          material={materials.Rock}
          position={[5.471, 29.18, -5.741]}
          scale={0}
        />
        <mesh
          name="Rocks_and_stuff009"
          castShadow
          receiveShadow
          geometry={nodes.Rocks_and_stuff009.geometry}
          material={materials.Rock}
          position={[5.471, 29.18, -5.741]}
          scale={0}
        />
        <mesh
          name="Rocks_and_stuff010"
          castShadow
          receiveShadow
          geometry={nodes.Rocks_and_stuff010.geometry}
          material={materials.Rock}
          position={[5.471, 29.18, -5.741]}
          scale={0}
        />
        <mesh
          name="Rocks_and_stuff011"
          castShadow
          receiveShadow
          geometry={nodes.Rocks_and_stuff011.geometry}
          material={materials.Rock}
          position={[5.471, 29.18, -5.741]}
          scale={0}
        />
        <mesh
          name="Rocks_and_stuff012"
          castShadow
          receiveShadow
          geometry={nodes.Rocks_and_stuff012.geometry}
          material={materials.Rock}
          position={[5.471, 29.18, -5.741]}
          scale={0}
        />
        <mesh
          name="Rocks_and_stuff013"
          castShadow
          receiveShadow
          geometry={nodes.Rocks_and_stuff013.geometry}
          material={materials.Rock}
          position={[5.471, 29.18, -5.741]}
          scale={0}
        />
        <mesh
          name="Rocks_and_stuff014"
          castShadow
          receiveShadow
          geometry={nodes.Rocks_and_stuff014.geometry}
          material={materials.Rock}
          position={[5.471, 29.18, -5.741]}
          scale={0}
        />
        <mesh
          name="Rocks_and_stuff015"
          castShadow
          receiveShadow
          geometry={nodes.Rocks_and_stuff015.geometry}
          material={materials.Rock}
          position={[5.471, 29.18, -5.741]}
          scale={0}
        />
        <mesh
          name="Rocks_and_stuff016"
          castShadow
          receiveShadow
          geometry={nodes.Rocks_and_stuff016.geometry}
          material={materials.Rock}
          position={[5.471, 29.18, -5.741]}
          scale={0}
        />
        <mesh
          name="Rocks_and_stuff017"
          castShadow
          receiveShadow
          geometry={nodes.Rocks_and_stuff017.geometry}
          material={materials.Rock}
          position={[5.471, 29.18, -5.741]}
          scale={0}
        />
        <mesh
          name="Rocks_and_stuff018"
          castShadow
          receiveShadow
          geometry={nodes.Rocks_and_stuff018.geometry}
          material={materials.Rock}
          position={[5.471, 29.18, -5.741]}
          scale={0}
        />
        <mesh
          name="Rocks_and_stuff019"
          castShadow
          receiveShadow
          geometry={nodes.Rocks_and_stuff019.geometry}
          material={materials.Rock}
          position={[5.471, 29.18, -5.741]}
          scale={0}
        />
        <mesh
          name="Rocks_and_stuff020"
          castShadow
          receiveShadow
          geometry={nodes.Rocks_and_stuff020.geometry}
          material={materials.Rock}
          position={[5.471, 29.18, -5.741]}
          scale={0}
        />
        <mesh
          name="Rocks_and_stuff021"
          castShadow
          receiveShadow
          geometry={nodes.Rocks_and_stuff021.geometry}
          material={materials.Rock}
          position={[5.471, 29.18, -5.741]}
          scale={0}
        />
        <mesh
          name="Rocks_and_stuff022"
          castShadow
          receiveShadow
          geometry={nodes.Rocks_and_stuff022.geometry}
          material={materials.Rock}
          position={[5.471, 29.18, -5.741]}
          scale={0}
        />
        <mesh
          name="Rocks_and_stuff023"
          castShadow
          receiveShadow
          geometry={nodes.Rocks_and_stuff023.geometry}
          material={materials.Rock}
          position={[5.471, 29.18, -5.741]}
          scale={0}
        />
        <mesh
          name="Rocks_and_stuff024"
          castShadow
          receiveShadow
          geometry={nodes.Rocks_and_stuff024.geometry}
          material={materials.Rock}
          position={[5.471, 29.18, -5.741]}
          scale={0}
        />
        <mesh
          name="Rocks_and_stuff025"
          castShadow
          receiveShadow
          geometry={nodes.Rocks_and_stuff025.geometry}
          material={materials.Rock}
          position={[5.471, 29.18, -5.741]}
          scale={0}
        />
        <mesh
          name="Aquarium_plant004"
          castShadow
          receiveShadow
          geometry={nodes.Aquarium_plant004.geometry}
          material={materials["Fish tank thing 1"]}
          position={[5.471, 29.18, -5.741]}
          scale={0}
        />
        <mesh
          name="Aquarium_plant"
          castShadow
          receiveShadow
          geometry={nodes.Aquarium_plant.geometry}
          material={materials["Fish thank thing 3"]}
          position={[5.471, 29.18, -5.741]}
          scale={0}
        />
        <mesh
          name="Aquarium_seaweed"
          castShadow
          receiveShadow
          geometry={nodes.Aquarium_seaweed.geometry}
          material={materials.Seaweed}
          position={[5.471, 29.18, -5.741]}
          scale={0}
        />
        <mesh
          name="Aquarium_plant001"
          castShadow
          receiveShadow
          geometry={nodes.Aquarium_plant001.geometry}
          material={materials["Fish tank thing 2"]}
          position={[5.471, 29.18, -5.741]}
          scale={0}
        />
        <mesh
          name="Aquarium_plant002"
          castShadow
          receiveShadow
          geometry={nodes.Aquarium_plant002.geometry}
          material={materials["Fish tank thing 1"]}
          position={[5.471, 29.18, -5.741]}
          scale={0}
        />
        <mesh
          name="Aquarium_plant003"
          castShadow
          receiveShadow
          geometry={nodes.Aquarium_plant003.geometry}
          material={materials["Fish tank thing 2"]}
          position={[5.471, 29.18, -5.741]}
          scale={0}
        />
        <mesh
          name="Aquarium_seaweed001"
          castShadow
          receiveShadow
          geometry={nodes.Aquarium_seaweed001.geometry}
          material={materials.Seaweed}
          position={[5.471, 29.18, -5.741]}
          scale={0}
        />
        <mesh
          name="Aquarium_seaweed002"
          castShadow
          receiveShadow
          geometry={nodes.Aquarium_seaweed002.geometry}
          material={materials.Seaweed}
          position={[5.471, 29.18, -5.741]}
          scale={0}
        />
        <mesh
          name="Aquarium_seaweed003"
          castShadow
          receiveShadow
          geometry={nodes.Aquarium_seaweed003.geometry}
          material={materials.Seaweed}
          position={[5.471, 29.18, -5.741]}
          scale={0}
        />
        <mesh
          name="Aquarium_seaweed004"
          castShadow
          receiveShadow
          geometry={nodes.Aquarium_seaweed004.geometry}
          material={materials.Seaweed}
          position={[5.471, 29.18, -5.741]}
          scale={0}
        />
        <mesh
          name="Aquarium_seaweed005"
          castShadow
          receiveShadow
          geometry={nodes.Aquarium_seaweed005.geometry}
          material={materials.Seaweed}
          position={[5.471, 29.18, -5.741]}
          scale={0}
        />
        <mesh
          name="Aquarium_seaweed006"
          castShadow
          receiveShadow
          geometry={nodes.Aquarium_seaweed006.geometry}
          material={materials.Seaweed}
          position={[5.471, 29.18, -5.741]}
          scale={0}
        />
        <mesh
          name="FloorFirst"
          castShadow
          receiveShadow
          geometry={nodes.FloorFirst.geometry}
          material={materials["Floor tile 1"]}
          position={[2.844, 31.017, 8.615]}
          scale={0}
        />
        <mesh
          name="Dirt"
          castShadow
          receiveShadow
          geometry={nodes.Dirt.geometry}
          material={materials.Dirt}
          position={[0.244, 31.017, 10.756]}
          scale={0}
        />
        <mesh
          name="FloorSecond"
          castShadow
          receiveShadow
          geometry={nodes.FloorSecond.geometry}
          material={materials["Floor tile 2"]}
          position={[2.627, 31.017, 9.836]}
          scale={0}
        />
        <mesh
          name="FloorThird"
          castShadow
          receiveShadow
          geometry={nodes.FloorThird.geometry}
          material={materials["Floor tile 3"]}
          position={[3.075, 31.017, 11.046]}
          scale={0}
        />
        <group name="Mailbox" position={[5.322, 1.002, 10.081]} scale={0}>
          <mesh
            name="Cylinder021"
            castShadow
            receiveShadow
            geometry={nodes.Cylinder021.geometry}
            material={materials.Pages}
          />
          <mesh
            name="Cylinder021_1"
            castShadow
            receiveShadow
            geometry={nodes.Cylinder021_1.geometry}
            material={materials["Book cover blue"]}
          />
          <mesh
            name="Cylinder021_2"
            castShadow
            receiveShadow
            geometry={nodes.Cylinder021_2.geometry}
            material={materials["Desk top.001"]}
          />
        </group>
        <group name="Lamp" position={[0.257, 1.001, 9.019]} scale={0}>
          <mesh
            name="Plane010"
            castShadow
            receiveShadow
            geometry={nodes.Plane010.geometry}
            material={materials.Lamp}
          />
          <mesh
            name="Plane010_1"
            castShadow
            receiveShadow
            geometry={nodes.Plane010_1.geometry}
            material={materials["Lamp light"]}
          />
        </group>
        <group name="WelcomeSign" position={[0.244, 31.031, 10.756]} scale={0}>
          <mesh
            name="Cylinder_1"
            castShadow
            receiveShadow
            geometry={nodes.Cylinder_1.geometry}
            material={materials.Sign}
          />
          <mesh
            name="Cylinder_2"
            castShadow
            receiveShadow
            geometry={nodes.Cylinder_2.geometry}
            material={materials["Welcome text"]}
          />
        </group>
        <group
          name="Mini_floor"
          position={[3.408, 0.874, 5.121]}
          rotation={[0, 0.001, 0]}
        >
          <mesh
            name="Cube081"
            castShadow
            receiveShadow
            geometry={nodes.Cube081.geometry}
            material={materials.Walls}
          />
          <mesh
            name="Cube081_1"
            castShadow
            receiveShadow
            geometry={nodes.Cube081_1.geometry}
            material={materials["Side floor"]}
          />
        </group>
        <group name="Desk" position={[34.698, 2.882, 3.634]} scale={0}>
          <mesh
            name="Cylinder014"
            castShadow
            receiveShadow
            geometry={nodes.Cylinder014.geometry}
            material={materials["Desk top.001"]}
          />
          <mesh
            name="Cylinder014_1"
            castShadow
            receiveShadow
            geometry={nodes.Cylinder014_1.geometry}
            material={materials["Desk legs.001"]}
          />
          <mesh
            name="Cylinder014_2"
            castShadow
            receiveShadow
            geometry={nodes.Cylinder014_2.geometry}
            material={materials["Desk leg black.001"]}
          />
        </group>
        <group name="Desk_plant" position={[-5.574, 4.538, -0.391]} scale={0}>
          <mesh
            name="Cube006"
            castShadow
            receiveShadow
            geometry={nodes.Cube006.geometry}
            material={materials.Leaves}
          />
          <mesh
            name="Cube006_1"
            castShadow
            receiveShadow
            geometry={nodes.Cube006_1.geometry}
            material={materials.Pot}
          />
          <mesh
            name="Cube006_2"
            castShadow
            receiveShadow
            geometry={nodes.Cube006_2.geometry}
            material={materials.Dirt}
          />
        </group>
        <group name="Mousepad" position={[-4.483, 3.434, 2.472]} scale={0}>
          <mesh
            name="Cube007"
            castShadow
            receiveShadow
            geometry={nodes.Cube007.geometry}
            material={materials["Trackpad base"]}
          />
          <mesh
            name="Cube007_1"
            castShadow
            receiveShadow
            geometry={nodes.Cube007_1.geometry}
            material={materials["Trackpad face"]}
          />
        </group>
        <group name="Pencil_case" position={[-5.959, 4.23, 5.606]} scale={0}>
          <mesh
            name="Cube085"
            castShadow
            receiveShadow
            geometry={nodes.Cube085.geometry}
            material={materials["Pencil base 2"]}
          />
          <mesh
            name="Cube085_1"
            castShadow
            receiveShadow
            geometry={nodes.Cube085_1.geometry}
            material={materials["Pencil holder"]}
          />
          <mesh
            name="Cube085_2"
            castShadow
            receiveShadow
            geometry={nodes.Cube085_2.geometry}
            material={materials["Pencil head"]}
          />
          <mesh
            name="Cube085_3"
            castShadow
            receiveShadow
            geometry={nodes.Cube085_3.geometry}
            material={materials["Pencil lead"]}
          />
          <mesh
            name="Cube085_4"
            castShadow
            receiveShadow
            geometry={nodes.Cube085_4.geometry}
            material={materials["Pencil base"]}
          />
        </group>
        <group name="Keyboard" position={[-4.508, 3.513, 3.776]} scale={0}>
          <mesh
            name="Cube088"
            castShadow
            receiveShadow
            geometry={nodes.Cube088.geometry}
            material={materials["White keys"]}
          />
          <mesh
            name="Cube088_1"
            castShadow
            receiveShadow
            geometry={nodes.Cube088_1.geometry}
            material={materials["Blue keys"]}
          />
          <mesh
            name="Cube088_2"
            castShadow
            receiveShadow
            geometry={nodes.Cube088_2.geometry}
            material={materials["Orange keys"]}
          />
          <mesh
            name="Cube088_3"
            castShadow
            receiveShadow
            geometry={nodes.Cube088_3.geometry}
            material={materials.Keyboard}
          />
        </group>
        <group name="Table" position={[3.326, 1.457, 31.699]} scale={0}>
          <mesh
            name="Cube128"
            castShadow
            receiveShadow
            geometry={nodes.Cube128.geometry}
            material={materials["Table legs"]}
          />
          <mesh
            name="Cube128_1"
            castShadow
            receiveShadow
            geometry={nodes.Cube128_1.geometry}
            material={materials.Table}
          />
        </group>
        <group name="Coffee_mug" position={[1.817, 2.922, 1.208]} scale={0}>
          <mesh
            name="Cube002"
            castShadow
            receiveShadow
            geometry={nodes.Cube002.geometry}
            material={materials.Dirt}
          />
          <mesh
            name="Cube002_1"
            castShadow
            receiveShadow
            geometry={nodes.Cube002_1.geometry}
            material={materials.Mug}
          />
        </group>
        <group name="Table_book_1" position={[2.218, 2.944, 0.585]} scale={0}>
          <mesh
            name="Cube003"
            castShadow
            receiveShadow
            geometry={nodes.Cube003.geometry}
            material={materials["Book cover blue"]}
          />
          <mesh
            name="Cube003_1"
            castShadow
            receiveShadow
            geometry={nodes.Cube003_1.geometry}
            material={materials.Pages}
          />
        </group>
        <group name="Table_book_2" position={[2.223, 2.88, 0.306]} scale={0}>
          <mesh
            name="Cube004"
            castShadow
            receiveShadow
            geometry={nodes.Cube004.geometry}
            material={materials["Book cover blue"]}
          />
          <mesh
            name="Cube004_1"
            castShadow
            receiveShadow
            geometry={nodes.Cube004_1.geometry}
            material={materials.Pages}
          />
        </group>
        <group name="Table_book_3" position={[2.564, 2.647, -0.149]} scale={0}>
          <mesh
            name="Cube005"
            castShadow
            receiveShadow
            geometry={nodes.Cube005.geometry}
            material={materials.Pages}
          />
          <mesh
            name="Cube005_1"
            castShadow
            receiveShadow
            geometry={nodes.Cube005_1.geometry}
            material={materials["Book cover green"]}
          />
        </group>
        <mesh
          name="Chair"
          castShadow
          receiveShadow
          geometry={nodes.Chair.geometry}
          material={materials.Chair}
          position={[-2.287, 2.782, 3.252]}
          scale={0}
        />
        <mesh
          name="Chair_legs"
          castShadow
          receiveShadow
          geometry={nodes.Chair_legs.geometry}
          material={materials["Floor tile 2"]}
          position={[-2.287, 1.387, 3.252]}
          scale={0}
        />
        <mesh
          name="Clock"
          castShadow
          receiveShadow
          geometry={nodes.Clock.geometry}
          material={materials["Desk top.001"]}
          position={[5.902, 11.744, -7.344]}
          scale={0}
        />
        <group name="Clock001" position={[5.902, 11.744, -7.344]} scale={0}>
          <mesh
            name="Cylinder001_1"
            castShadow
            receiveShadow
            geometry={nodes.Cylinder001_1.geometry}
            material={materials["Desk top.001"]}
          />
          <mesh
            name="Cylinder001_2"
            castShadow
            receiveShadow
            geometry={nodes.Cylinder001_2.geometry}
            material={materials.Pages}
          />
        </group>
        <group name="Clock002" position={[5.902, 11.744, -7.344]} scale={0}>
          <mesh
            name="Cylinder006_1"
            castShadow
            receiveShadow
            geometry={nodes.Cylinder006_1.geometry}
            material={materials["Desk top.001"]}
          />
          <mesh
            name="Cylinder006_2"
            castShadow
            receiveShadow
            geometry={nodes.Cylinder006_2.geometry}
            material={materials.Pages}
          />
        </group>
        <mesh
          name="Ceiling_lamp"
          castShadow
          receiveShadow
          geometry={nodes.Ceiling_lamp.geometry}
          material={materials["Ceiling light"]}
          position={[2.439, 21.406, 0.125]}
          scale={0}
        />
        <mesh
          name="Ceiling_lamp_rod"
          castShadow
          receiveShadow
          geometry={nodes.Ceiling_lamp_rod.geometry}
          material={materials["Ceiling rod"]}
          position={[0.908, 21.406, 0.123]}
          rotation={[Math.PI, -0.001, Math.PI]}
          scale={[1, 0, 0]}
        />
        <mesh
          name="Couch"
          castShadow
          receiveShadow
          geometry={nodes.Couch.geometry}
          material={materials.Couch}
          position={[-2.022, 32.235, -5.488]}
          scale={0}
        />
        <mesh
          name="Cushion_1"
          castShadow
          receiveShadow
          geometry={nodes.Cushion_1.geometry}
          material={materials["Couch cushions"]}
          position={[-4.496, 3.76, 36.278]}
          scale={0}
        />
        <mesh
          name="Cushion_2"
          castShadow
          receiveShadow
          geometry={nodes.Cushion_2.geometry}
          material={materials["Couch cushions"]}
          position={[-2.009, 3.76, 36.278]}
          scale={0}
        />
        <mesh
          name="Cushion_3"
          castShadow
          receiveShadow
          geometry={nodes.Cushion_3.geometry}
          material={materials["Couch cushions"]}
          position={[0.48, 3.76, 36.278]}
          scale={0}
        />
        <mesh
          name="Pillow"
          castShadow
          receiveShadow
          geometry={nodes.Pillow.geometry}
          material={materials.Pillow}
          position={[-0.501, 33.575, -5.933]}
          scale={0}
        />
        <mesh
          name="Blanket"
          castShadow
          receiveShadow
          geometry={nodes.Blanket.geometry}
          material={materials.Blanket}
          position={[-0.862, 35.333, -5.089]}
          scale={0}
        />
        <mesh
          name="Shelves"
          castShadow
          receiveShadow
          geometry={nodes.Shelves.geometry}
          material={materials["Desk top.001"]}
          position={[-2.985, 8.534, -6.829]}
          rotation={[-0.299, 0, 0]}
          scale={[0, 1, 0]}
        />
        <mesh
          name="Shelves001"
          castShadow
          receiveShadow
          geometry={nodes.Shelves001.geometry}
          material={materials["Desk top.001"]}
          position={[-6.055, 8.636, 3.603]}
          rotation={[-0.299, 0, 0]}
          scale={[0, 1, 0]}
        />
        <mesh
          name="Shelves002"
          castShadow
          receiveShadow
          geometry={nodes.Shelves002.geometry}
          material={materials["Desk top.001"]}
          position={[-6.055, 10.804, 2.704]}
          rotation={[-0.299, 0, 0]}
          scale={[0, 1, 0]}
        />
        <group name="Book_1" position={[-6.07, 10.888, 2.881]} scale={0}>
          <mesh
            name="Cube072"
            castShadow
            receiveShadow
            geometry={nodes.Cube072.geometry}
            material={materials["Book cover red"]}
          />
          <mesh
            name="Cube072_1"
            castShadow
            receiveShadow
            geometry={nodes.Cube072_1.geometry}
            material={materials.Pages}
          />
        </group>
        <group name="Book_2" position={[-6.02, 10.98, 2.865]} scale={0}>
          <mesh
            name="Cube073"
            castShadow
            receiveShadow
            geometry={nodes.Cube073.geometry}
            material={materials.Pages}
          />
          <mesh
            name="Cube073_1"
            castShadow
            receiveShadow
            geometry={nodes.Cube073_1.geometry}
            material={materials["Book cover green"]}
          />
        </group>
        <group name="Book_3" position={[-6.089, 11.074, 2.879]} scale={0}>
          <mesh
            name="Cube074"
            castShadow
            receiveShadow
            geometry={nodes.Cube074.geometry}
            material={materials.Pages}
          />
          <mesh
            name="Cube074_1"
            castShadow
            receiveShadow
            geometry={nodes.Cube074_1.geometry}
            material={materials["Book cover blue"]}
          />
        </group>
        <group name="Book_4" position={[-6.009, 11.163, 2.112]} scale={0}>
          <mesh
            name="Cube075"
            castShadow
            receiveShadow
            geometry={nodes.Cube075.geometry}
            material={materials["Book cover red"]}
          />
          <mesh
            name="Cube075_1"
            castShadow
            receiveShadow
            geometry={nodes.Cube075_1.geometry}
            material={materials.Pages}
          />
        </group>
        <group name="Book_5" position={[-6.009, 11.163, 2.022]} scale={0}>
          <mesh
            name="Cube076"
            castShadow
            receiveShadow
            geometry={nodes.Cube076.geometry}
            material={materials.Pages}
          />
          <mesh
            name="Cube076_1"
            castShadow
            receiveShadow
            geometry={nodes.Cube076_1.geometry}
            material={materials["Book cover blue"]}
          />
        </group>
        <group name="Book_6" position={[-6.009, 11.163, 1.931]} scale={0}>
          <mesh
            name="Cube077"
            castShadow
            receiveShadow
            geometry={nodes.Cube077.geometry}
            material={materials.Pages}
          />
          <mesh
            name="Cube077_1"
            castShadow
            receiveShadow
            geometry={nodes.Cube077_1.geometry}
            material={materials["Book cover green"]}
          />
        </group>
        <group name="Book_7" position={[-6.01, 11.148, 1.714]} scale={0}>
          <mesh
            name="Cube078"
            castShadow
            receiveShadow
            geometry={nodes.Cube078.geometry}
            material={materials.Pages}
          />
          <mesh
            name="Cube078_1"
            castShadow
            receiveShadow
            geometry={nodes.Cube078_1.geometry}
            material={materials["Book cover brown"]}
          />
        </group>
        <group name="Box" position={[-5.904, 9.076, 2.935]} scale={0}>
          <mesh
            name="Cube084"
            castShadow
            receiveShadow
            geometry={nodes.Cube084.geometry}
            material={materials["Blue keys"]}
          />
          <mesh
            name="Cube084_1"
            castShadow
            receiveShadow
            geometry={nodes.Cube084_1.geometry}
            material={materials["Box top"]}
          />
        </group>
        <group
          name="Picture_frame"
          position={[-4.273, 9.096, -7.287]}
          scale={0}
        >
          <mesh
            name="Cube116"
            castShadow
            receiveShadow
            geometry={nodes.Cube116.geometry}
            material={materials["Picture frame"]}
          />
          <mesh
            name="Cube116_1"
            castShadow
            receiveShadow
            geometry={nodes.Cube116_1.geometry}
            material={materials.Picture}
          />
        </group>
        <group name="Shelf_lamp" position={[-5.998, 9.169, 4.833]} scale={0}>
          <mesh
            name="Cube079"
            castShadow
            receiveShadow
            geometry={nodes.Cube079.geometry}
            material={materials.Pages}
          />
          <mesh
            name="Cube079_1"
            castShadow
            receiveShadow
            geometry={nodes.Cube079_1.geometry}
            material={materials["Lamp base"]}
          />
        </group>
        <group name="Shelf_plant" position={[-6.029, 11.345, 3.674]} scale={0}>
          <mesh
            name="Cube070"
            castShadow
            receiveShadow
            geometry={nodes.Cube070.geometry}
            material={materials.Leaves}
          />
          <mesh
            name="Cube070_1"
            castShadow
            receiveShadow
            geometry={nodes.Cube070_1.geometry}
            material={materials["Pot 2"]}
          />
          <mesh
            name="Cube070_2"
            castShadow
            receiveShadow
            geometry={nodes.Cube070_2.geometry}
            material={materials.Dirt}
          />
        </group>
        <group name="Cylinder" position={[-3.428, 33.9, -6.738]} scale={0}>
          <mesh
            name="Cylinder009"
            castShadow
            receiveShadow
            geometry={nodes.Cylinder009.geometry}
            material={materials["Bottle 1"]}
          />
          <mesh
            name="Cylinder009_1"
            castShadow
            receiveShadow
            geometry={nodes.Cylinder009_1.geometry}
            material={materials["Bottle cap"]}
          />
        </group>
        <group name="Cylinder001" position={[-2.705, 33.819, -7.044]} scale={0}>
          <mesh
            name="Cylinder010"
            castShadow
            receiveShadow
            geometry={nodes.Cylinder010.geometry}
            material={materials["Bottle 2"]}
          />
          <mesh
            name="Cylinder010_1"
            castShadow
            receiveShadow
            geometry={nodes.Cylinder010_1.geometry}
            material={materials["Bottle cap"]}
          />
        </group>
        <group name="Cylinder005" position={[-2.096, 33.901, -6.695]} scale={0}>
          <mesh
            name="Cylinder011"
            castShadow
            receiveShadow
            geometry={nodes.Cylinder011.geometry}
            material={materials["Bottle 3"]}
          />
          <mesh
            name="Cylinder011_1"
            castShadow
            receiveShadow
            geometry={nodes.Cylinder011_1.geometry}
            material={materials["Bottle cap"]}
          />
        </group>
        <group name="Cylinder006" position={[-1.506, 34.247, -7.093]} scale={0}>
          <mesh
            name="Cylinder012"
            castShadow
            receiveShadow
            geometry={nodes.Cylinder012.geometry}
            material={materials["Bottle 4"]}
          />
          <mesh
            name="Cylinder012_1"
            castShadow
            receiveShadow
            geometry={nodes.Cylinder012_1.geometry}
            material={materials["Bottle cap"]}
          />
        </group>
      </group>
    </animated.group>
  );
}

useGLTF.preload("/models/website ver2.glb");
